### ISSUE TITLE
Mocking of classes without constructor does not work in Spock 1.1-groovy-2.4-rc-3

### ISSUE THREAD

**Issue by mkordas** [spockframework/spock#684]
# Issue description
When trying to mock a class without constructor using Spock `1.1-groovy-2.4-rc-3` and `"net.bytebuddy:byte-buddy:1.5.9"` on classpath I'm getting.

` java.lang.NoSuchMethodError: net.bytebuddy.implementation.FieldAccessor.ofField(Ljava/lang/String;)Lnet/bytebuddy/implementation/FieldAccessor$FieldDefinable;`

# How to reproduce
```
testCompile "org.spockframework:spock-core:1.1-groovy-2.4-rc-3"
testCompile "net.bytebuddy:byte-buddy:1.5.9"`
```
```java
        given: 'sample class without default constructor'
        EnumMap map = Mock(EnumMap)

        when:
        map.clear()

        then:
        1 * map.clear()
```

Exception:
```
    java.lang.NoSuchMethodError: net.bytebuddy.implementation.FieldAccessor.ofField(Ljava/lang/String;)Lnet/bytebuddy/implementation/FieldAccessor$FieldDefinable;
        at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory.createMock(ProxyBasedMockFactory.java:115)
        at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:63)
        at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
        at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
        at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
        at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
        at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
        at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:99)
```

# Additional Environment information

## Java/JDK
`1.8`

## Groovy version
`2.4.7`

## Operating System
Windows

**Comment by szpak** [comment]
Duplicate of #678.

**Comment by mkordas** [comment]
@szpak thanks, I'm closing this one then

**Comment by mkordas** [comment]
@robfletcher is there any chance to have rc-4 released soon?

**Comment by szpak** [comment]
It would be good to merge #682 before :)

**Comment by mihaianghel** [comment]
Hi guys, is there a planned release for this issue ? Thanks

**Comment by vanta** [comment]
Same here
