### ISSUE TITLE
Can't run spock tests with JDK 14

### ISSUE THREAD

**Issue by KamilJedrzejuk** [spockframework/spock#1142]
Hello the problem is described here:
https://issues.apache.org/jira/browse/GROOVY-9505

I'm getting error:
Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 

I'm using a Gradle 6.3
Open JDK 14
Spring Boot 2.4
2.0-M2-groovy-3.0

 

The code you can find here https://github.com/KamilJedrzejuk/weatherinformer/tree/develop

**Comment by szpak** [comment]
While testing Spock itself with Java 14 is blocked by #1139 (OSGI plugin migration to be able run Spock build with Gradle 6.3), it should work in the majority of cases. I took a look at it and it doesn't seem to be Spock related.

Running the build with Java 14 from the develop branch I have:
```
> Task :compileTestGroovy FAILED
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
        at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.parseGroovyVersion(ApiGroovyCompiler.java:325)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:168)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:68)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:94)
        at org.gradle.api.internal.tasks.compile.GroovyCompilerFactory$DaemonSideCompiler.execute(GroovyCompilerFactory.java:75)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
...
```

It may suggest some problem with Groovy version.

Examination of the dependencies shows that insteead of Groovy 3.0.x 2.5.9 is used:
```
$ gw dependencies --configuration testRuntimeClasspath | grep -A10 spock | head -n 5
+--- org.spockframework:spock-core:2.0-M2-groovy-3.0
|    +--- org.codehaus.groovy:groovy:3.0.0 -> 2.5.9
|    +--- org.codehaus.groovy:groovy-json:3.0.0 -> 2.5.9
|    |    \--- org.codehaus.groovy:groovy:2.5.9
|    +--- org.codehaus.groovy:groovy-nio:3.0.0 -> 2.5.9
```

For Java 14 at least 2.5.10 is required (or 3.x). What enforces 2.5.x?

```
$ gw dependencyInsight --configuration testRuntimeClasspath --dependency org.codehaus.groovy:groovy

```
...
org.codehaus.groovy:groovy:3.0.0 -> 2.5.9
+--- org.spockframework:spock-core:2.0-M2-groovy-3.0
|    +--- testRuntimeClasspath
|    \--- org.spockframework:spock-spring:2.0-M2-groovy-3.0
|         \--- testRuntimeClasspath
\--- org.spockframework:spock-spring:2.0-M2-groovy-3.0 (*)

org.codehaus.groovy:groovy-json:2.5.9 (selected by rule)
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 14
   ]
...
```

Which suggest some Gradle rule. The spring-boot plugin comes to mind. As spring-boot 2.2.6 added [support for Java 14](https://jaxenter.com/spring-boot-2-2-6-170386.html) (you use 2.2.4) bumping a version is the first thing to do. Unfortunately 2.2.6 still uses Groovy 2.5.10 which works with Java 14, but uses ASM 7 and it fails with:

```
> Task :compileTestGroovy FAILED
startup failed:
General error during conversion: This feature requires ASM8_EXPERIMENTAL

java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
        at groovyjarjarasm.asm.ClassVisitor.visitRecordComponentExperimental(ClassVisitor.java:304)
        at groovyjarjarasm.asm.ClassReader.readRecordComponent(ClassReader.java:929)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:704)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:401)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
```

Records are supported in ASM 8 which is [available as a dependency in Groovy 3.0.3+](https://github.com/apache/groovy/commit/973d4586c19577b0c3d02e237cf3289a18dc4ebf). It is a shaded dependency, so it would be hard to override it in 2.5.10. To make it work you could remove the record usage from your code, but it's not the perfect solution for your case :).

It is possible to force Groovy 3.0.3 with spring-boot 2.2.6 by putting:
> groovy.version=3.0.3

in gradle.properties. However it still fails with:
```
> Task :compileTestGroovy FAILED
startup failed:
General error during conversion: This feature requires ASM8

java.lang.UnsupportedOperationException: This feature requires ASM8
        at groovyjarjarasm.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:306)
        at groovyjarjarasm.asm.ClassReader.readRecordComponent(ClassReader.java:927)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:705)
        at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:401)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
...
``

which brings us to [that line in CompilerConfiguration](https://github.com/apache/groovy/blob/a9946449a943fcf55204f8bbfaa71f3419500f2a/src/main/java/org/codehaus/groovy/control/CompilerConfiguration.java#L125
)

And here is a question to @paulk-asert:
Can Groovy (3.0.3) interact with `record` defined in Java 14 production code?

**Comment by szpak** [comment]
Closing here as not Spock specific and (most likely) explained in [GROOVY-9505](https://issues.apache.org/jira/browse/GROOVY-9505) with the Groovy PR proposal in https://github.com/apache/groovy/pull/1222.
