### ISSUE TITLE
NoSuchMethodError with byte-buddy 1.5.x

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#678]
Spock 1.1-groovy-2.4-rc-3 fails on a stub creation for a class if byte-buddy 1.5.x is on a classpath.

```
java.lang.NoSuchMethodError: net.bytebuddy.implementation.FieldAccessor.ofField(Ljava/lang/String;)Lnet/bytebuddy/implementation/FieldAccessor$FieldDefinable;

	at org.spockframework.mock.runtime.ProxyBasedMockFactory$ByteBuddyMockFactory.createMock(ProxyBasedMockFactory.java:115)
	at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:63)
	at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
	at org.spockframework.lang.SpecInternals.StubImpl(SpecInternals.java:131)
	at info.solidsoft.gradle.cdeliveryboy.PreconfigurationBannerSpec.setup(PreconfigurationBannerSpec.groovy:16)
```

Tested with 1.5.0 and 1.5.9. It works fine with BB 1.4.x.

//CC: @raphw

**Comment by raphw** [comment]
I had to slightly change the API in 1.5+, unfortunately. The good news: better, faster byte code. We should upgrade anyways as explained in: https://github.com/spockframework/spock/pull/663

**Comment by szpak** [comment]
It was a long time ago that I forgot about #663. I will ping the team to merge it.

**Comment by szpak** [comment]
#663 is merged. The change/fix should be included in rc-4.

**Comment by mihaianghel** [comment]
hi @szpak , is there an estimate for 1.1-groovy-2.4-rc-4 ? Thank you

**Comment by szpak** [comment]
I have no idea :(. You need to ask @robfletcher or @sbglasius.

**Comment by mihaianghel** [comment]
Hi @robfletcher , @sbglasius , is there an estimate for the new RC - 1.1-groovy-2.4-rc-4  ? Thank you
