### ISSUE TITLE
Referencing a `where` variable more than once results in compile error when using `2.4-M5-groovy-4.0`

### ISSUE THREAD

**Issue by pavelfomin** [spockframework/spock#2142]
### Describe the bug

Referencing a `where clause` variable from the left _more than once_ results in `The current scope already contains a variable of the name a` and ` java.lang.StackOverflowError` when using `2.4-M5-groovy-4.0` but works fine in `2.4-M4-groovy-4.0` and earlier versions.

### To Reproduce

Example of using `a` more than once in `b` (the last scenario results in java.lang.StackOverflowError, other scenarios still work):
```groovy
    def "reference variable in where clause more than once"() {

        expect:
        true

        where:
        a    | b
        null | a
        1    | a
        2    | a + a
    }
```

### Expected behavior

should compile correctly and run w/out issues

### Actual behavior

```
The current scope already contains a variable of the name a
 @ line -1, column -1.
1 error


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':compileTestGroovy'.
> Compilation failed; see the compiler error output for details.

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)
```

### Java version

17

### Buildtool version

$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

The same result for two different gradle versions:
$ ./gradlew -version
Gradle 8.11

$ ./gradlew -version
Gradle 7.5.1

### What operating system are you using

Mac

### Dependencies

2.4-M5-groovy-4.0

**Comment by pavelfomin** [comment]
Example above in https://github.com/pavelfomin/spring-boot-rest-example/pull/35

**Comment by Vampire** [comment]
Thanks, but this is a duplicate and already fixed for the next release
